version: "3.8"
services:
  web:
    image: ramazantufekci/phpappexample:latest
    hostname: "ramazanpc"
    ports:
      - "81:80"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
